export class ProjectProfile {
    number: string;
    name: string;
    project_type: number;
    contract_type: number;
    Address: string;
    state: string;
    zipcode: string;
    country: number;
    timezone: number;
    length: string;
    area: string;
    volumn: string;
    angle: string;
    length_rounding: string;
    area_rounding: string;
    volumn_rounding: string;
    angle_rounding: string;
    geolocation_1: string;
    geolocation_2: string;
    geolocation_3: string;
    geolocation_4: string;
    bim_template: string;
    thumb_image: string;
    is_archive?: boolean;
    template_title?: string;
    created_by: string;
    created_time: string;
}